### PR TITLE
Update Tokio to 1.0

### PR DESCRIPTION
**Pull request by simnalamburt**
Tokio 1.0 has significantly improved features over 0.2, let's use it!

I'm using this patched version in https://github.com/femiwiki/sns-discord and it's working!

By submitting this pull request:
- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

**Comment by simnalamburt** [comment]
Oops I found something wrong with this PR, please don't merge it yet.

**Review by calavera — COMMENTED** [review]
woow! Thanks for doing this. I'll run some smoke tests and will merge it if everything looks good.

**Review by calavera — CHANGES_REQUESTED** [review]
Unfortunately, this doesn't seem to work as expected 😿 

When I try to run a simple http function I get this error:

```
DEBU[0101] Start runtime                                
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/io/driver/mod.rs:263:18
```

This is the code I run: https://github.com/netlify/rust-functions-example/blob/main/src/main.rs

[Update] I think I'm missing a change in my code.

**Review by calavera — APPROVED** [review]
It seems to work now 🎊 

Thanks a lot for you contribution. I'll release a new version this week, and I'll ping you in this thread when it's available in crates.io

**Comment by calavera** [comment]
@simnalamburt I've released 0.2.0 with this change and other bug fixes. Thanks again for helping with this! 🎊

**Comment by simnalamburt** [comment]
@calavera Thanks for the works! The existence of this repository should certainly be known to more people.

**Pull request merged**
